# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ravi Mohan Polymer Informatics Portfolio
email: ravimohan19@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Polymer Informatics is a budding field that utilizes data-driven approaches to 
  solve complex problems in polymer science. Some of the common problems are accurate representation of polymers,
  computation of properties at different scales, prediction of usability in end product applications,
  and understanding of the degradation and wear in service and storage. My research focuses on these areas,
  and the portfolio contains my work in this field.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  ravimohan01

# Author information
author:
  name: Ravi Mohan
  email: ravimohan19@gmail.com
  picture: /assets/images/profile-picture.jpg
  bio: >-
    Polymer Informatics researcher focused on data-driven approaches to 
    solve complex problems in polymer science including accurate representation of polymers,
    computation of properties at different scales, and prediction of usability in end applications.

# Build settings
theme: minima
#remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
